config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  resources :tweets do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, presence: true, length: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if params[:back]
      render :new
    else
      if @tweet.save
        redirect_to tweets_path
      else
        render :new
      end
    end
  end

  def confirm
    @tweet = Tweet.new(tweet_params)
    render :new if @tweet.invalid?
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweets_path
    else
      render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>春の大喜利祭り</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <header>
      <h1>春の大喜利祭り</h1>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
    <div class="footer">
      <p>@mayu_nishikawa</p>
    </div>
    </footer>
  </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, local: true, url: choose_new_or_edit) do |form| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="tweet_content">
    <%= form.text_area :content, size: "70x5" %><br>
    <%= form.submit 'ボケる' %>
  </div>
<% end %>

app/views/tweets/confirm.html.erb
<section class="sub_page_topic">
  <h1>これで勝負しますか?</h1>
</section>

<section class="form">
  <%= form_with(model: @tweet, local: true, url: tweets_path) do |form| %>
    <%= form.hidden_field :content %>

    <p>本文:<%= @tweet.content %></p>
    <%= form.submit  "ボケる" %>
    <%= form.submit '戻る', name: 'back' %>
  <% end %>
</section>

app/views/tweets/edit.html.erb
<section class="sub_page_topic">
  <h1><span>編集</span></h1>
  <p>お題：入社初日に出会った、衝撃的な先輩プログラマーとは</p>
</section>

<section>
  <%= render 'form' %>
  <%= link_to 'Topページに戻ってみんなのボケをみる', tweets_path, class: "link_to_top" %>
</section>

app/views/tweets/index.html.erb
<section>
  <p>表示されているお題で自由に<%= link_to 'ボケてみよう！', new_tweet_path %></p>
  <p class="topic">お題：入社初日に出会った、衝撃的な先輩プログラマーとは</p>
</section>
<section class="jokebox">
  <table>
    <tr>
      <th>みんなのボケ</th>
      <th>詳細</th>
      <th>編集</th>
      <th>削除</th>
    </tr>

    <% @tweets.each do |tweet| %>
    <tr>
      <td><%= tweet.content %></td>
      <td><%= link_to 'click', tweet_path(tweet.id) %></td>
      <td><%= link_to 'click', edit_tweet_path(tweet.id) %></td>
      <td><%= link_to 'click', tweet_path(tweet.id), method: :delete, data: { confirm: 'なかったことにしますか?'} %></td>
    </tr>
    <% end %>
  </table>
  <%= link_to 'ボケてみる', new_tweet_path, class: "link_to_tweet" %>
</section>

app/views/tweets/new.html.erb
<section class="sub_page_topic">
  <h1><span>投稿</span></h1>
  <p>お題：入社初日に出会った、衝撃的な先輩プログラマーとは</p>
</section>

<section>
  <%= render 'form' %>
  <%= link_to 'Topページに戻ってみんなのボケをみる', tweets_path, class: "link_to_top" %>
</section>

app/views/tweets/show.html.erb
<section class="sub_page_topic">
  <h1><span>詳細</span></h1>
  <p>お題：入社初日に出会った、衝撃的な先輩プログラマーとは</p>
</section>

<section>
  <p>ボケ: <%= @tweet.content %></p>
  <%= link_to 'Topページに戻ってみんなのボケをみる', tweets_path, class: "link_to_top" %>
</section>